#!/usr/bin/env python3
"""Append the fifth manually reviewed full-answer batch (ANS-126 through ANS-150)."""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "content" / "answer-layers.json"
REVIEWED_ON = "2026-08-15"


def layer(identifier, topic, question, short, model, assumptions, traps, followups):
    return {"id": identifier, "topic": topic, "question": question, "shortAnswer": short, "modelAnswer": model, "assumptions": assumptions, "traps": traps, "followUps": followups, "reviewedOn": REVIEWED_ON, "status": "reviewed-full-v1"}


BATCH = [
layer("ANS-126","Thermodynamics","What is the difference between heat and work?","Heat and work are boundary-crossing energy-transfer modes, not properties stored in a system; heat is driven by temperature difference, while work is organized transfer through generalized forces and displacements.","After defining the system boundary and sign convention, the first law writes the change in internal energy as heat added minus work done by the system. Heat transfer occurs because of a temperature difference; work includes boundary, electrical, shaft, or other generalized force–displacement transfer. Both are path dependent, so a state does not contain a quantity of heat or work after the process. Their microscopic distinction can depend on the chosen boundary and coarse-grained description, while internal energy is a state function.",["System boundary and sign convention specified","Initial and final states are thermodynamic states"],["Saying heat is energy stored in a hot body","Calling every energy transfer with moving particles work"],["Give a piston example.","Why are δQ and δW inexact?","Can adiabatic work change temperature?","How does electrical work enter?","What changes for an open system?"]),
layer("ANS-127","Basic Electronics and Instrumentation","Why does a capacitor block DC but pass AC?","An ideal capacitor current is i=C dv/dt: after a DC transient its voltage is constant and current is zero, while a changing voltage produces current with impedance magnitude 1/(ωC).","For an ideal capacitor q=Cv, differentiation gives i=C dv/dt. Under a finite DC step the capacitor charges during a transient; at long-time steady state dv/dt=0, so ideal capacitor current vanishes. For sinusoidal steady state Z_C=1/(jωC), so impedance decreases with frequency. “Passes AC” is circuit-dependent: source and load impedances, coupling topology, leakage, dielectric loss, parasitic inductance, voltage rating, and transient initial conditions determine the actual response.",["Linear ideal capacitance for governing relation","Sinusoidal steady state only when using impedance"],["Saying no current ever flows with DC","Saying every AC frequency passes unchanged"],["Derive RC transient.","What happens at ω→0?","Why does voltage not jump?","What is leakage?","When do parasitics dominate?"]),
layer("ANS-128","Radar Fundamentals","What is the basic idea of radar range measurement?","A pulsed radar estimates slant range from echo delay, R=cΔt/2 for a monostatic system, after detecting and associating a returned waveform.","The transmitter emits a known waveform and the receiver estimates the delay of energy scattered back from a target. In a simple monostatic geometry the round trip gives R=cΔt/2. Practical measurement requires synchronized timing, waveform bandwidth, matched filtering, detection threshold, calibration, and correct association. Range is distinct from range resolution, accuracy, maximum unambiguous range, and maximum detectable range; clutter, multipath, propagation, noise, target scattering, and processing affect those quantities.",["Monostatic round-trip geometry for factor two","Propagation speed approximately c in the stated medium"],["Forgetting the return path factor two","Confusing range with resolution or detection limit"],["What sets range resolution?","What is ambiguity?","How does bandwidth enter?","How does clutter matter?","What changes in bistatic radar?"]),
layer("ANS-129","Radiation Protection","What is the difference between irradiation and radioactive contamination?","Irradiation means being exposed to a radiation field; contamination means radioactive material is present on or inside a person, object, or area and can persist or spread.","An external source can irradiate a body without transferring radioactive material; removing or shielding the source ends that field exposure. Contamination is material and therefore requires monitoring, containment, and authorized decontamination or internal-exposure assessment. Irradiation can cause activation only for suitable nuclear reactions and energies; it is not automatic. In a real suspected event I would stop work, avoid spreading material, notify qualified radiation-protection personnel, and follow the facility procedure rather than improvising.",["Conceptual distinction, not incident-specific advice","Facility procedure and authorized monitoring control real response"],["Calling every irradiated object contaminated","Attempting cleanup before monitoring and authorization"],["External versus internal exposure?","What is activation?","How do monitors differ?","Why can contamination spread?","What is the first safe action?"]),
layer("ANS-130","Classical Mechanics","What is the difference between inertial and non-inertial frames?","In an inertial frame a free particle moves at constant velocity and Newton’s laws take their standard form; an accelerating or rotating frame needs inertial-force terms to preserve that form.","Frames related by constant-velocity translations are inertial in Newtonian mechanics. In a frame with translational acceleration, rotation, or changing rotation rate, observed acceleration includes frame terms. Rewriting m a_inertial=F_real in rotating coordinates introduces translational, Coriolis, centrifugal, and Euler inertial forces with signs set by the transformation. These are not new interactions, but they have measurable frame-relative consequences. The origin, axes, angular velocity, and approximation must be stated.",["Newtonian nonrelativistic mechanics","Frame kinematics are known and differentiable"],["Calling an inertial frame one that is merely at rest","Treating centrifugal force as a new fundamental interaction"],["Give elevator example.","Direction of Coriolis force?","Does Coriolis do work?","What is Euler force?","How does GR change the concept?"]),
layer("ANS-131","Materials Science","Why does synthesis temperature affect phase formation?","Temperature changes both thermodynamic driving forces and kinetic rates such as diffusion, nucleation, reaction, volatilization, and defect equilibration, so different temperature–time paths can produce different phases.","The stable phase at a given composition and environment minimizes the appropriate free energy, but reaching it requires transport and reaction across barriers. Raising temperature can increase diffusion and reaction rates, alter nucleation versus growth, change precursor decomposition, oxidation state, vapor loss, defect populations, grain growth, and container interaction. Temperature alone is incomplete: dwell, ramp/cooling rate, atmosphere, pressure, stoichiometry, mixing, and thermal calibration matter. I would compare controlled batches and verify phase with calibrated complementary evidence.",["Actual composition, atmosphere, and pressure specified","Temperature profile and calibration known"],["Saying higher temperature always improves crystallinity or purity","Changing temperature and several other parameters simultaneously"],["Thermodynamics versus kinetics?","Why does dwell matter?","How atmosphere changes result?","What is a control series?","What result falsifies the interpretation?"]),
layer("ANS-132","Nuclear Physics","What is a chain reaction?","A nuclear chain reaction occurs when products of one reaction, commonly neutrons from fission, induce further reactions; its average behavior is described by multiplication, leakage, absorption, and feedback.","For a multiplying fission system, neutrons from one generation may cause later fissions. The effective multiplication factor compares neutron populations after production, absorption, and leakage: below one the chain decreases, at one it is steady, and above one it grows under the modeled state. Power dynamics also depend on prompt and delayed neutrons, thermal/material feedback, geometry, controls, and heat removal. This is a conceptual explanation only; operation and criticality control belong to authorized facilities and procedures.",["Generation-averaged conceptual model","No operational manipulation or design instruction"],["Equating chain reaction automatically with an explosion","Ignoring leakage, absorption, delayed neutrons, and feedback"],["What is k_eff?","Why delayed neutrons matter?","What does moderator do?","How do control rods differ?","Why can critical be normal?"]),
layer("ANS-133","Solid State Physics","What is a crystal defect?","A crystal defect is a departure from ideal periodic structure, such as point defects, dislocations, interfaces, or extended disorder, characterized relative to a stated crystal model.","Point defects include vacancies, interstitials, substitutions, and antisites; line defects are dislocations; planar defects include grain boundaries and stacking faults; volume defects include pores or precipitates. Defects can alter carrier density and scattering, diffusion, mechanical strength, optical transitions, magnetism, and phase behavior. Their effect is not universally harmful. Evidence needs a technique sensitive to the defect type and scale, because XRD peak width, microscopy, spectroscopy, or transport alone rarely identifies every defect uniquely.",["Reference ideal structure and composition defined","Defect concentration and dimensional scale distinguished"],["Calling every impurity a defect without a reference model","Assuming defects always reduce performance"],["Vacancy versus interstitial?","What is a dislocation?","How affect diffusion?","How detect defects?","Can defects improve conductivity?"]),
layer("ANS-134","Spacecraft Systems","Why do satellites need attitude control?","Satellites need controlled orientation and angular rate to point payloads and antennas, manage power and thermal geometry, execute maneuvers, and maintain safe configurations.","Attitude determination estimates orientation and rate from sensors; attitude control uses actuators such as reaction wheels, magnetorquers, or thrusters through a control law. Requirements come from payload line of sight, communication, solar-array illumination, drag/thermal constraints, and safe mode. Disturbance torques, sensor bias, structural flexibility, actuator saturation, momentum dumping, power, and failure modes limit performance. Not every mission needs the same pointing accuracy or control architecture.",["Reference frames and pointing requirement defined","Spacecraft treated as a rigid body only where justified"],["Confusing attitude determination with control","Saying reaction wheels can store unlimited momentum"],["Why star tracker?","How magnetorquer works?","What causes disturbance torque?","What is safe mode?","How verify pointing?"]),
layer("ANS-135","Radiation Protection","What is dose equivalent?","Equivalent dose weights absorbed dose in an organ/tissue by radiation-type factors to reflect differing biological effectiveness; its SI unit is sievert, not becquerel or gray.","Absorbed dose is deposited energy per mass in gray. Equivalent dose H_T=Σ_R w_R D_T,R applies radiation weighting factors to absorbed dose in a specified tissue; effective dose additionally applies tissue weighting factors and is a protection quantity for populations under defined standards. These quantities are not detector count rate, activity, or an individualized prediction of harm. Exact factors, operational quantities, limits, and monitoring decisions must come from current authorized radiation-protection standards and personnel.",["Protection-quantity definitions and current standard specified","No patient/worker-specific inference from generic numbers"],["Equating sievert with activity","Calling equivalent dose a directly measured universal biological injury"],["Gray versus sievert?","Equivalent versus effective dose?","What is activity?","How is monitoring related?","Why must standards be current?"]),
layer("ANS-136","Thermodynamics","When is a process reversible?","A reversible process is an ideal limiting path that can be reversed while restoring system and surroundings with no net entropy generation; it requires equilibrium approached through infinitesimal driving differences and no dissipative effects.","Quasistatic motion alone is insufficient: friction, viscosity, electrical resistance, finite temperature differences, mixing, diffusion, inelastic deformation, and uncontrolled reactions generate entropy even if the system passes slowly through near-equilibrium states. Reversibility is assessed for the complete system plus surroundings, not only the working substance. It is useful as a bound and calculational path, but finite-rate practical processes are irreversible and exact reversibility typically implies vanishing power.",["Equilibrium endpoint states and complete boundary specified","No hidden dissipative process"],["Equating slow with reversible","Assessing only system entropy and ignoring surroundings"],["Quasistatic versus reversible?","Why zero entropy generation?","Can heat transfer be reversible?","Why power tends to zero?","Give a friction example."]),
layer("ANS-137","Solid State Physics","What is the Debye model trying to explain?","The Debye model approximates a solid’s acoustic vibrations as a continuum with a cutoff chosen to preserve the number of modes, explaining the low-temperature T³ lattice heat capacity and high-temperature classical limit.","It assumes linear acoustic dispersion up to a Debye cutoff and counts three polarizations in an isotropic continuum. Quantizing those modes and applying Bose occupation yields C_V proportional to T³ at temperatures well below the Debye temperature and approaches 3Nk_B at high temperature. The model captures broad lattice heat-capacity trends but omits detailed phonon dispersion, optical branches, anisotropy, anharmonicity, electronic heat capacity, and structural complexity.",["Harmonic isotropic continuum with acoustic modes","Cutoff enforces 3N vibrational modes"],["Calling Debye temperature a phase-transition temperature","Using the model to predict detailed phonon spectra"],["Why T³?","What is cutoff?","Compare Einstein model.","Why Dulong–Petit limit?","When does model fail?"]),
layer("ANS-138","Magnetism","Why can a material be magnetic?","Magnetism arises from electronic orbital and spin moments plus their response and interactions; exchange, band structure, anisotropy, temperature, defects, and domains determine the macroscopic state.","Closed shells usually give weak diamagnetism, while unpaired moments can produce paramagnetism. Quantum-mechanical exchange can favor ordered ferro-, antiferro-, or ferrimagnetic states below characteristic temperatures, while itinerant electrons require band-based descriptions. The measured response also includes domains, anisotropy, demagnetizing field, impurities, substrate/background, and hysteresis. A magnetic loop alone is not proof of intrinsic bulk ferromagnetism; controls and temperature/field dependence are needed.",["Magnetic field convention and sample geometry stated","Electronic structure and temperature regime specified"],["Explaining ferromagnetism as classical dipoles simply lining up","Treating any hysteresis as intrinsic sample magnetism"],["Dia- versus paramagnetism?","What is exchange?","Why domains form?","What is Curie temperature?","How test impurity magnetism?"]),
layer("ANS-139","Basic Electronics and Instrumentation","What is a filter?","A filter is a system with a frequency-dependent transfer function used to shape signal or noise content; its useful behavior includes magnitude, phase, bandwidth, order, loading, and transient response.","Low-pass, high-pass, band-pass, and notch filters are defined by their pass and stop regions, but ideal brick-wall behavior is noncausal or impractical. A first-order RC low-pass has cutoff 1/(2πRC) under stated source/load conditions and introduces phase shift. Real designs trade selectivity, delay, ringing, dynamic range, component tolerance, active-device limits, and noise. An anti-alias filter must be analog and matched to the sampling rate and signal band.",["Linear time-invariant small-signal model where transfer function is used","Source, load, and sampling context specified"],["Calling filtering removal of all noise","Ignoring phase, transient, and loading effects"],["Derive RC cutoff.","What is −3 dB?","Why higher order?","What is group delay?","Why anti-alias filter?"]),
layer("ANS-140","Instrumentation and EMC","Why is grounding important?","Grounding defines reference and return paths and can support safety, shielding, and controlled current flow; poor topology creates loops, common-impedance coupling, noise, or hazards.","I would distinguish protective earth, chassis, signal reference, and cable shield rather than call them all zero volts. The objective is to control where normal, fault, displacement, and interference currents flow. Single-point, multipoint, differential, or hybrid strategies depend on frequency, geometry, impedance, and safety standards. Ground is not an infinite sink, and connecting more points can worsen a loop. I would draw the complete return path and verify with impedance, common-mode, and EMC measurements.",["Electrical safety rules and system architecture specified","Frequency-dependent conductor impedance recognized"],["Assuming every ground node has identical potential","Using signal ground as a substitute for protective earth"],["Ground versus shield?","What is ground loop?","Why twist differential pair?","Single versus multipoint?","How test common-mode noise?"]),
layer("ANS-141","Mathematical Physics","Why are eigenvalues important?","Eigenvalues identify invariant-mode scales of a linear operator and often correspond to measurable frequencies, energies, decay rates, principal axes, or stability growth rates under a physical model.","For Av=λv, the eigenvector direction is preserved up to scaling. Expanding dynamics in an eigenbasis can decouple normal modes, diagonalize Hermitian observables, expose stability, and simplify repeated evolution. Physical meaning depends on operator, domain, boundary conditions, inner product, units, and completeness. Degeneracy, non-normal operators, defective matrices, and numerical conditioning can complicate the simple picture; not every computed eigenvalue is observable.",["Linear operator and domain/boundary conditions defined","Relevant inner product and units specified"],["Calling eigenvalues important merely because a determinant vanishes","Ignoring non-Hermitian conditioning and incomplete eigenvectors"],["Normal-mode example?","Hermitian eigenvalue property?","What is degeneracy?","How boundary quantizes?","What is conditioning?"]),
layer("ANS-142","Statistical Mechanics","Why is the canonical ensemble appropriate?","It describes a subsystem exchanging energy with a much larger reservoir at fixed temperature while volume and particle number are fixed and coupling is weak.","Consider an isolated total system with fixed energy. The probability that the subsystem has energy E_i is proportional to the reservoir multiplicity at E_total−E_i. Expanding reservoir entropy gives the Boltzmann factor exp(−βE_i), normalized by Z. The approximation needs a large equilibrium bath, weak coupling, and well-defined temperature; finite baths, strong coupling, nonequilibrium driving, conserved quantities, or long-range interactions can invalidate or modify it.",["Weak system–bath coupling and equilibrium","Fixed subsystem V and N for canonical ensemble"],["Saying the subsystem energy is fixed","Using canonical statistics under strong nonequilibrium drive without test"],["Derive Boltzmann factor.","What fluctuates?","Canonical versus microcanonical?","What is Z?","When ensembles differ?"]),
layer("ANS-143","Statistical Mechanics","Why do fermions obey Fermi-Dirac statistics?","Identical fermions have antisymmetric many-particle states, so a single-particle quantum state cannot be multiply occupied; equilibrium counting then gives the Fermi–Dirac distribution.","Exchanging identical fermions changes the many-body wavefunction sign. If two fermions occupy the same complete single-particle state, antisymmetry makes the state vanish, which is Pauli exclusion. Maximizing multiplicity or using the grand partition function with occupation zero or one yields f(E)=1/[exp((E−μ)/kT)+1]. Indistinguishability alone is not enough—bosons are also indistinguishable but symmetric. Interactions can change quasiparticles and spectra, while fermionic antisymmetry remains fundamental.",["Identical fermions in equilibrium","Single-particle state and chemical potential defined"],["Attributing FD statistics only to indistinguishability","Saying no two fermions can share the same spatial orbital regardless spin"],["Derive occupation.","What happens at T=0?","Bosons difference?","What is Fermi energy?","How do interactions enter?"]),
layer("ANS-144","Materials Microstructure","What is the difference between crystallite and grain?","A crystallite is a coherently diffracting domain, while a grain is a microstructural region bounded by grain boundaries and may contain multiple subgrains or coherently diffracting domains.","XRD line broadening can estimate a coherence length under a size/strain/instrument model; it is not automatically particle or grain size. A grain is usually identified microstructurally by orientation and boundaries using microscopy or diffraction mapping, and a particle may contain one or many grains. Defects, low-angle boundaries, twins, strain, texture, segmentation, and sampling affect comparisons. The terms should be tied to the measurement method and scale rather than used interchangeably.",["Measurement definition and spatial/coherence scale stated","Instrument broadening and representative sampling considered"],["Calling Scherrer size grain or particle size universally","Assuming every visible particle is a single crystal"],["How measure grain size?","What is coherent domain?","How strain broadens XRD?","What is subgrain?","Why methods disagree?"]),
layer("ANS-145","Basic Electronics and Instrumentation","What is slew rate?","Slew rate is the maximum large-signal rate of output-voltage change, commonly V/s, imposed by internal current and capacitance limits; it is distinct from small-signal bandwidth.","An amplifier can satisfy a small-signal gain-bandwidth estimate yet distort a large, fast sine wave because the required maximum slope 2πfV_peak exceeds its slew rate. Slew limiting produces nonlinear, often triangular-looking output and longer settling. The value depends on device, compensation, load, supply, and operating conditions. I would check both small-signal frequency response and large-signal step/sine behavior, plus saturation and output-current limits.",["Large-signal amplifier regime","Specified load, amplitude, and supply conditions"],["Equating slew rate with bandwidth","Ignoring signal amplitude when checking distortion"],["Sine-wave slope condition?","How observe slew limiting?","Why compensation matters?","Slew versus settling?","What about output current?"]),
layer("ANS-146","Sampling and Instrumentation","Why is sampling theorem not enough for real instruments?","Nyquist’s condition assumes a truly band-limited signal and ideal sampling/reconstruction; real sensors need anti-alias filtering, adequate acquisition bandwidth, timing quality, dynamic range, and noise/error control.","The theorem says a band-limited signal can be reconstructed from samples above twice its highest frequency under ideal conditions. Physical signals and noise are not perfectly band limited, an ADC input has aperture and bandwidth limits, clocks have jitter, quantization and saturation occur, and finite records cause leakage and resolution trade-offs. An analog anti-alias filter must attenuate content before sampling, with transition band and margin. Sampling rate also does not determine amplitude accuracy, effective bits, or identifiability by itself.",["Linear sampling of a suitably band-limited signal","Reconstruction and timing model stated"],["Saying any signal sampled above twice a nominal frequency is safe","Trying to remove aliasing after irreversible folding"],["What is aliasing?","Why analog filter?","How jitter matters?","Record length effect?","Oversampling benefit?"]),
layer("ANS-147","Mathematical and Quantum Physics","What makes an operator Hermitian?","Formally, an operator A is Hermitian on a stated domain if ⟨φ,Aψ⟩=⟨Aφ,ψ⟩ for all domain states; physical observables require the stronger self-adjoint domain condition.","Integration by parts may make a differential expression look Hermitian, but boundary terms and domains decide the operator. A self-adjoint operator equals its adjoint including the domain, giving real spectrum and unitary spectral structure under appropriate conditions. Finite Hermitian matrices avoid many domain subtleties, but infinite-dimensional momentum or Hamiltonian operators do not. I would state the Hilbert space, inner product, boundary conditions, and domain before claiming observable status.",["Hilbert-space inner product defined","Dense domain and boundary conditions specified"],["Checking only that a matrix expression equals its conjugate transpose while ignoring domain","Using Hermitian and self-adjoint as universally identical"],["Why eigenvalues real?","Give boundary-term example.","Momentum on interval?","What is adjoint domain?","Why observable self-adjoint?"]),
layer("ANS-148","Mathematical Physics","What is a Green function physically?","A Green function is the response of a linear operator with specified boundary/initial conditions to a point or impulse source; superposition builds the response to a general source.","For L G(x,x′)=δ(x−x′), the solution of Lψ=f can be written as an integral of G against f, plus homogeneous terms as required. G encodes propagation, geometry, causality, boundaries, and the operator spectrum, so there is not one Green function for a differential expression without conditions. Retarded, advanced, static, and frequency-domain Green functions answer different physical questions. Singularities and normalization must be interpreted with units and distributions.",["Linear operator and domain specified","Boundary/initial or causality condition specified"],["Calling G merely an inverse matrix without conditions","Forgetting homogeneous solution or null modes"],["Point-source example?","Retarded versus advanced?","How eigenfunction expansion works?","What are units?","When inverse fails?"]),
layer("ANS-149","Experimental Methods","Why repeat a measurement?","Repetition estimates variability, detects drift or heterogeneity, tests stability, and supports uncertainty—but only when the repeated conditions and independence level are defined.","Repeated readings on one setup estimate short-term repeatability, not batch-to-batch reproducibility. I would distinguish repeated acquisitions, positions, preparations, operators, days, and instruments; randomize order where drift or bias can matter; preserve all runs; and inspect residual/time trends rather than average blindly. More repeats reduce uncertainty of a mean for appropriate independent random variation, but they do not remove calibration bias, model error, or correlated drift.",["Repeat condition and measurand defined","Dependence/correlation between repeats considered"],["Calling many scans independent samples","Assuming averaging removes systematic effects"],["Repeatability versus reproducibility?","How many repeats?","Why randomize order?","How detect drift?","When mean is misleading?"]),
layer("ANS-150","Scientific Communication and Data","What makes a graph scientifically useful?","A useful graph makes the question, quantities, units, uncertainty, data provenance, model comparison, and relevant structure readable without distorting evidence.","I would label axes with quantity and unit, use a justified scale and range, show raw or appropriately summarized data, identify uncertainty definitions, and distinguish data from fits or guides. Captions should state conditions, sample size, normalization, and processing. Residuals or alternative views may reveal model failure hidden by a smooth fit. A graph should avoid truncated or dual axes that mislead, decorative interpolation, cherry-picked ranges, unsupported significant figures, and inaccessible colour-only encoding.",["Underlying data and processing traceable","Audience and scientific comparison defined"],["Optimizing appearance instead of evidential clarity","Using R² or a smooth curve as proof of the model"],["When use log scale?","How show uncertainty?","Why residual plot?","How avoid colour-only encoding?","What belongs in caption?"])
]


def main() -> None:
    data = json.loads(PATH.read_text())
    base = [row for row in data["layers"] if int(row["id"].split("-")[1]) < 126]
    later = [row for row in data["layers"] if int(row["id"].split("-")[1]) > 150]
    assert len(base) == 125, "Batch 5 builder expects the first 125 layers"
    assert len(BATCH) == 25
    assert len({row["id"] for row in BATCH}) == 25
    assert len({row["question"].lower() for row in BATCH}) == 25
    data["layers"] = sorted(base + BATCH + later, key=lambda row: int(row["id"].split("-")[1]))
    assert len(data["layers"]) == 150 + len(later)
    PATH.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n")
    print(f"Wrote answer batch 5; total reviewed layers: {len(data['layers'])}")


if __name__ == "__main__":
    main()
