#!/usr/bin/env python3
"""Append reviewed non-project answer batch 13 (ANS-326 and ANS-327)."""
from __future__ import annotations
import json
from pathlib import Path
R=Path(__file__).resolve().parents[1];P=R/'content'/'answer-layers.json';D='2026-08-15'
def L(i,q,s,m,a,tr,f):return {'id':f'ANS-{i:03d}','topic':'Experimental Contradictions','question':q,'shortAnswer':s,'modelAnswer':m,'assumptions':a,'traps':tr,'followUps':f,'reviewedOn':D,'status':'reviewed-full-v1'}
B=[
L(326,'What if your expected peak is absent?','First verify sensitivity, calibration, range, background and sample identity; then treat absence as a bounded nondetection that may challenge the assignment or model.','I would not add a peak through processing or immediately blame the instrument. I would check reference/standard response, acquisition range and resolution, baseline, expected intensity, overlap, preparation, orientation and detection limit. The feature may be genuinely absent, too weak, shifted, broadened or masked. I would report the nondetection with sensitivity and choose a complementary or higher-sensitivity test that distinguishes these explanations.', ['Expected feature and instrument response defined','Detection limit and sample history available'],['Calling nondetection proof of absence without sensitivity','Changing baseline until a peak appears'],['Was standard detected?','Could peak shift?','What overlap?','Which complementary method?','How report upper bound?']),
L(327,'What if the control shows the same trend as the sample?','The trend is not yet attributable to the sample-specific variable; audit whether the control is appropriate and test shared preparation, environment, instrument or analysis causes.','I would preserve both results, verify labels and acquisition order, and compare magnitude with uncertainty. A shared trend can indicate background, drift, solvent/substrate/container effect, handling, batch history or a response common to both. The control may also be poorly designed or contaminated. I would add a blank or orthogonal control and vary the proposed causal factor. Until separated, I would withdraw the sample-specific claim rather than subtract the control opportunistically.', ['Control intended to isolate one causal factor','Matched acquisition and uncertainty available'],['Ignoring the control because the sample signal is larger','Subtracting without a physical normalization model'],['Is control appropriate?','Could drift explain both?','Which blank next?','How compare uncertainty?','What claim remains safe?'])]
def main():
 d=json.loads(P.read_text());base=[x for x in d['layers'] if int(x['id'].split('-')[1])<326];later=[x for x in d['layers'] if int(x['id'].split('-')[1])>327];assert len(base)==325;d['layers']=sorted(base+B+later,key=lambda x:int(x['id'].split('-')[1]));assert len(B)==2 and len({x['id'] for x in d['layers']})==len(d['layers']);P.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');print(f"Wrote answer batch 13; total reviewed layers: {len(d['layers'])}")
if __name__=='__main__':main()
